[package]
name = "number_game"
version = "0.1.0"
authors = ["qween supercoder <yellowhatcrow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
